name: Action!

on:
  workflow_dispatch:

jobs:
  some-action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shell
        run: |
          docker-compose run shell